### ISSUE TITLE
documentation update about size()

### ISSUE THREAD

**Issue by debug-ito** [Leont/list-doublelinked#1]
The POD says that size() method runs in linear time, but the current implementation runs it in constant time.
The POD should be updated.

**Comment by Leont** [comment]
Yeah, that was changed in the last release but the docs weren't updated.

**Comment by Leont** [comment]
Actually, I reverted this. The next version will gain a `O(1)` splice method in return (which is often more useful in a linked list).

**Comment by debug-ito** [comment]
OK then. Thanks!
