### ISSUE TITLE
How should I iterate over all elements in a list?

### ISSUE THREAD

**Issue by debug-ito** [Leont/list-doublelinked#2]
I have trouble iterating over ALL elements in the list.

Currently, I can think of two ways:
- Use size() method to know how many times I should iterate. Even if size() runs in constant time, the code would look ugly.
- Catch an exception from next() or previous() method of Iterator. But there is no documentation about the exception, so I don't want to rely on that.

I suggest adding is_first() and is_last() methods to Iterator. That way, we can iterate the whole list safely.

**Comment by Leont** [comment]
You're supposed to use `begin` and `end` for that, but that part is rather underdeveloped. I remembered I had this part working, but after not having touched this code for 3 years it seems I was mistaken in thinking that. Must fix that though.

`is_first` and `is_last` might work for that, will have to think about it.

**Comment by debug-ito** [comment]
Thanks for the reply.

I think current iterator would also be problematic if the list is empty. Maybe this is another issue.

Anyway, I'm changing my mind to use arrays for my problem instead of List::DoubleLinked. So if you don't have time, just ignore this issue :)

**Comment by Leont** [comment]
In 0.004, this should work conceptually the same as in C++. that is:

```
for (my $iter = $list->begin; $iter != $list->end; $iter = $iter->next) {
  do_something($iter->value)
}
```

**Comment by debug-ito** [comment]
Thanks!
