### ISSUE TITLE
erase() method is broken

### ISSUE THREAD

**Issue by TheAthlete** [Leont/list-doublelinked#4]
Hello!
I am use erase() method for remove element under iterator and and get the error:

Not a HASH reference at /home/theathlete/perl5/lib/perl5/List/DoubleLinked.pm line 156.

Test script

```
#!/usr/bin/env perl 
use strict;
use warnings;
use feature 'say';

use List::DoubleLinked;

my $list = List::DoubleLinked->new(qw/foo bar baz/);

my $iter = $list->begin;
while (my $text = $iter->get) {
    $list->erase($iter) if $text eq 'bar';
    $iter = $iter->next;
}
```

Output:

>  $  perl test.pl
> Not a HASH reference at /home/theathlete/perl5/lib/perl5/List/DoubleLinked.pm line 156.

**Comment by Leont** [comment]
Yeah, that method was rather buggy, it should be fixed in the most recent release. I made erase return the next iterator, given that it invalidates the current one. Though you're not iterating over it in the correct way, you should compare the iterator against `$list->end`

```
my $iter = $list->begin;
while ($iter != $list->end) {
    my $text = $iter->get;
    $iter = ($text eq 'bar') ? $list->erase($iter) : $iter->next
}
```
